/*
 * SecBot API
 * API for integrating SecBot into external systems.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.alphabot.secbot.client.v0.codegen.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TestRunApiStartResponse
 */

public class TestRunApiStartResponse {
  @JsonProperty("testRunId")
  private String testRunId = null;

  public TestRunApiStartResponse testRunId(String testRunId) {
    this.testRunId = testRunId;
    return this;
  }

   /**
   * Get testRunId
   * @return testRunId
  **/
  @ApiModelProperty(value = "")
  public String getTestRunId() {
    return testRunId;
  }

  public void setTestRunId(String testRunId) {
    this.testRunId = testRunId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestRunApiStartResponse testRunApiStartResponse = (TestRunApiStartResponse) o;
    return Objects.equals(this.testRunId, testRunApiStartResponse.testRunId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(testRunId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestRunApiStartResponse {\n");
    
    sb.append("    testRunId: ").append(toIndentedString(testRunId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

