/*
 * SecBot API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.alphabot.secbot.client.v0.codegen.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;

/**
 * TestRunApiResponse
 */

public class TestRunApiResponse {
  @JsonProperty("testRunId")
  private String testRunId = null;

  @JsonProperty("status")
  private Integer status = null;

  @JsonProperty("startTime")
  private OffsetDateTime startTime = null;

  @JsonProperty("endTime")
  private OffsetDateTime endTime = null;

  @JsonProperty("failedTestCount")
  private Integer failedTestCount = null;

  @JsonProperty("successfulTestCount")
  private Integer successfulTestCount = null;

  @JsonProperty("totalTestCount")
  private Integer totalTestCount = null;

  public TestRunApiResponse testRunId(String testRunId) {
    this.testRunId = testRunId;
    return this;
  }

   /**
   * Get testRunId
   * @return testRunId
  **/
  @ApiModelProperty(value = "")
  public String getTestRunId() {
    return testRunId;
  }

  public void setTestRunId(String testRunId) {
    this.testRunId = testRunId;
  }

  public TestRunApiResponse status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public TestRunApiResponse startTime(OffsetDateTime startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Get startTime
   * @return startTime
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getStartTime() {
    return startTime;
  }

  public void setStartTime(OffsetDateTime startTime) {
    this.startTime = startTime;
  }

  public TestRunApiResponse endTime(OffsetDateTime endTime) {
    this.endTime = endTime;
    return this;
  }

   /**
   * Get endTime
   * @return endTime
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getEndTime() {
    return endTime;
  }

  public void setEndTime(OffsetDateTime endTime) {
    this.endTime = endTime;
  }

  public TestRunApiResponse failedTestCount(Integer failedTestCount) {
    this.failedTestCount = failedTestCount;
    return this;
  }

   /**
   * Get failedTestCount
   * @return failedTestCount
  **/
  @ApiModelProperty(value = "")
  public Integer getFailedTestCount() {
    return failedTestCount;
  }

  public void setFailedTestCount(Integer failedTestCount) {
    this.failedTestCount = failedTestCount;
  }

  public TestRunApiResponse successfulTestCount(Integer successfulTestCount) {
    this.successfulTestCount = successfulTestCount;
    return this;
  }

   /**
   * Get successfulTestCount
   * @return successfulTestCount
  **/
  @ApiModelProperty(value = "")
  public Integer getSuccessfulTestCount() {
    return successfulTestCount;
  }

  public void setSuccessfulTestCount(Integer successfulTestCount) {
    this.successfulTestCount = successfulTestCount;
  }

  public TestRunApiResponse totalTestCount(Integer totalTestCount) {
    this.totalTestCount = totalTestCount;
    return this;
  }

   /**
   * Get totalTestCount
   * @return totalTestCount
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalTestCount() {
    return totalTestCount;
  }

  public void setTotalTestCount(Integer totalTestCount) {
    this.totalTestCount = totalTestCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TestRunApiResponse testRunApiResponse = (TestRunApiResponse) o;
    return Objects.equals(this.testRunId, testRunApiResponse.testRunId) &&
        Objects.equals(this.status, testRunApiResponse.status) &&
        Objects.equals(this.startTime, testRunApiResponse.startTime) &&
        Objects.equals(this.endTime, testRunApiResponse.endTime) &&
        Objects.equals(this.failedTestCount, testRunApiResponse.failedTestCount) &&
        Objects.equals(this.successfulTestCount, testRunApiResponse.successfulTestCount) &&
        Objects.equals(this.totalTestCount, testRunApiResponse.totalTestCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(testRunId, status, startTime, endTime, failedTestCount, successfulTestCount, totalTestCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TestRunApiResponse {\n");
    
    sb.append("    testRunId: ").append(toIndentedString(testRunId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    endTime: ").append(toIndentedString(endTime)).append("\n");
    sb.append("    failedTestCount: ").append(toIndentedString(failedTestCount)).append("\n");
    sb.append("    successfulTestCount: ").append(toIndentedString(successfulTestCount)).append("\n");
    sb.append("    totalTestCount: ").append(toIndentedString(totalTestCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

