/*
 * SecBot API
 * API for integrating SecBot into external systems.
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.alphabot.secbot.client.v0.codegen;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;

import com.alphabot.secbot.client.v0.ApiClient;
import com.alphabot.secbot.client.v0.codegen.model.TestRunApiResponse;
import com.alphabot.secbot.client.v0.codegen.model.TestRunApiStartResponse;

/**
 * Basic API tests as sample
 */
@Ignore
public class SecBotApiTest {
	
	private SecBotApi api;

    private static String SECBOT_BASE_URL = "";
    private static String API_KEY = "";
    private static String PROJECT_ID = "";
    private static String ENV_ID = "";
    
    @Before
    public void setup() {
        ApiClient apiClient = new ApiClient().setBasePath(SECBOT_BASE_URL);
        apiClient.setApiKey(API_KEY);
        apiClient.setApiKeyPrefix("Bearer");
        api = new SecBotApi(apiClient);
    }
    
    @Test
    public void getLastTestRunTest() {
        TestRunApiResponse response = api.getLastTestRun(PROJECT_ID, ENV_ID);
        assertEquals(32, response.getTestRunId().length());
    }
    
    @Test
    public void getTestRunByIdTest() {
        String testRunId = "";
        TestRunApiResponse response = api.getTestRunById(PROJECT_ID, ENV_ID, testRunId);
        assertEquals(testRunId, response.getTestRunId());
    }
    
    @Test
    public void startTestRunTest() {
        TestRunApiStartResponse response = api.startTestRun(PROJECT_ID, ENV_ID);
        assertEquals(32, response.getTestRunId().length());
    }
    
}
